# Generated by Django 4.0.5 on 2022-06-18 09:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('file', models.FileField(upload_to='media/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service_id', models.CharField(max_length=10)),
                ('service_type', models.CharField(choices=[('USER', 'USER'), ('COMPANY', 'COMPANY'), ('SERVICE', 'SERVICE')], max_length=255)),
            ],
        ),
    ]
